function params=initparams()
% Returns an 'options' structure with default values for options

params=struct(  'gradmode','fd',...
                'fstepsize',1.5,...
                'bstepsize',0.8,...
                'gradtol',1e-6,...
                'contol',1e-4,...
                'maxunconiter',500,...
                'maxconiter',100,...
                'conetheta',89.5,...
                'fdstepsize',1e-8,...
                'restartevery',20,...
                'penaltynumberstart',10,...
                'penaltynumbermult', 10, ...
                'verbose','on', ...
                'unconalgo', 'secant' ...
            );

end